# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/anubhav/kv_server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/anubhav/kv_server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anubhav/kv_server/CMakeFiles /home/anubhav/kv_server//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anubhav/kv_server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kv_server

# Build rule for target.
kv_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kv_server
.PHONY : kv_server

# fast build rule for target.
kv_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_server.dir/build.make CMakeFiles/kv_server.dir/build
.PHONY : kv_server/fast

#=============================================================================
# Target rules for targets named kv_client

# Build rule for target.
kv_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kv_client
.PHONY : kv_client

# fast build rule for target.
kv_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_client.dir/build.make CMakeFiles/kv_client.dir/build
.PHONY : kv_client/fast

#=============================================================================
# Target rules for targets named distributed_load_client

# Build rule for target.
distributed_load_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 distributed_load_client
.PHONY : distributed_load_client

# fast build rule for target.
distributed_load_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_load_client.dir/build.make CMakeFiles/distributed_load_client.dir/build
.PHONY : distributed_load_client/fast

#=============================================================================
# Target rules for targets named conflict_test

# Build rule for target.
conflict_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 conflict_test
.PHONY : conflict_test

# fast build rule for target.
conflict_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conflict_test.dir/build.make CMakeFiles/conflict_test.dir/build
.PHONY : conflict_test/fast

#=============================================================================
# Target rules for targets named redis_server

# Build rule for target.
redis_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 redis_server
.PHONY : redis_server

# fast build rule for target.
redis_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_server.dir/build.make CMakeFiles/redis_server.dir/build
.PHONY : redis_server/fast

generated/kv.grpc.pb.o: generated/kv.grpc.pb.cc.o
.PHONY : generated/kv.grpc.pb.o

# target to build an object file
generated/kv.grpc.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_server.dir/build.make CMakeFiles/kv_server.dir/generated/kv.grpc.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_client.dir/build.make CMakeFiles/kv_client.dir/generated/kv.grpc.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_load_client.dir/build.make CMakeFiles/distributed_load_client.dir/generated/kv.grpc.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conflict_test.dir/build.make CMakeFiles/conflict_test.dir/generated/kv.grpc.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_server.dir/build.make CMakeFiles/redis_server.dir/generated/kv.grpc.pb.cc.o
.PHONY : generated/kv.grpc.pb.cc.o

generated/kv.grpc.pb.i: generated/kv.grpc.pb.cc.i
.PHONY : generated/kv.grpc.pb.i

# target to preprocess a source file
generated/kv.grpc.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_server.dir/build.make CMakeFiles/kv_server.dir/generated/kv.grpc.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_client.dir/build.make CMakeFiles/kv_client.dir/generated/kv.grpc.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_load_client.dir/build.make CMakeFiles/distributed_load_client.dir/generated/kv.grpc.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conflict_test.dir/build.make CMakeFiles/conflict_test.dir/generated/kv.grpc.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_server.dir/build.make CMakeFiles/redis_server.dir/generated/kv.grpc.pb.cc.i
.PHONY : generated/kv.grpc.pb.cc.i

generated/kv.grpc.pb.s: generated/kv.grpc.pb.cc.s
.PHONY : generated/kv.grpc.pb.s

# target to generate assembly for a file
generated/kv.grpc.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_server.dir/build.make CMakeFiles/kv_server.dir/generated/kv.grpc.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_client.dir/build.make CMakeFiles/kv_client.dir/generated/kv.grpc.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_load_client.dir/build.make CMakeFiles/distributed_load_client.dir/generated/kv.grpc.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conflict_test.dir/build.make CMakeFiles/conflict_test.dir/generated/kv.grpc.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_server.dir/build.make CMakeFiles/redis_server.dir/generated/kv.grpc.pb.cc.s
.PHONY : generated/kv.grpc.pb.cc.s

generated/kv.pb.o: generated/kv.pb.cc.o
.PHONY : generated/kv.pb.o

# target to build an object file
generated/kv.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_server.dir/build.make CMakeFiles/kv_server.dir/generated/kv.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_client.dir/build.make CMakeFiles/kv_client.dir/generated/kv.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_load_client.dir/build.make CMakeFiles/distributed_load_client.dir/generated/kv.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conflict_test.dir/build.make CMakeFiles/conflict_test.dir/generated/kv.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_server.dir/build.make CMakeFiles/redis_server.dir/generated/kv.pb.cc.o
.PHONY : generated/kv.pb.cc.o

generated/kv.pb.i: generated/kv.pb.cc.i
.PHONY : generated/kv.pb.i

# target to preprocess a source file
generated/kv.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_server.dir/build.make CMakeFiles/kv_server.dir/generated/kv.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_client.dir/build.make CMakeFiles/kv_client.dir/generated/kv.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_load_client.dir/build.make CMakeFiles/distributed_load_client.dir/generated/kv.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conflict_test.dir/build.make CMakeFiles/conflict_test.dir/generated/kv.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_server.dir/build.make CMakeFiles/redis_server.dir/generated/kv.pb.cc.i
.PHONY : generated/kv.pb.cc.i

generated/kv.pb.s: generated/kv.pb.cc.s
.PHONY : generated/kv.pb.s

# target to generate assembly for a file
generated/kv.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_server.dir/build.make CMakeFiles/kv_server.dir/generated/kv.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_client.dir/build.make CMakeFiles/kv_client.dir/generated/kv.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_load_client.dir/build.make CMakeFiles/distributed_load_client.dir/generated/kv.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conflict_test.dir/build.make CMakeFiles/conflict_test.dir/generated/kv.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_server.dir/build.make CMakeFiles/redis_server.dir/generated/kv.pb.cc.s
.PHONY : generated/kv.pb.cc.s

kv_load_client/conflict_test.o: kv_load_client/conflict_test.cpp.o
.PHONY : kv_load_client/conflict_test.o

# target to build an object file
kv_load_client/conflict_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conflict_test.dir/build.make CMakeFiles/conflict_test.dir/kv_load_client/conflict_test.cpp.o
.PHONY : kv_load_client/conflict_test.cpp.o

kv_load_client/conflict_test.i: kv_load_client/conflict_test.cpp.i
.PHONY : kv_load_client/conflict_test.i

# target to preprocess a source file
kv_load_client/conflict_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conflict_test.dir/build.make CMakeFiles/conflict_test.dir/kv_load_client/conflict_test.cpp.i
.PHONY : kv_load_client/conflict_test.cpp.i

kv_load_client/conflict_test.s: kv_load_client/conflict_test.cpp.s
.PHONY : kv_load_client/conflict_test.s

# target to generate assembly for a file
kv_load_client/conflict_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conflict_test.dir/build.make CMakeFiles/conflict_test.dir/kv_load_client/conflict_test.cpp.s
.PHONY : kv_load_client/conflict_test.cpp.s

kv_load_client/distributed_load_client.o: kv_load_client/distributed_load_client.cpp.o
.PHONY : kv_load_client/distributed_load_client.o

# target to build an object file
kv_load_client/distributed_load_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_load_client.dir/build.make CMakeFiles/distributed_load_client.dir/kv_load_client/distributed_load_client.cpp.o
.PHONY : kv_load_client/distributed_load_client.cpp.o

kv_load_client/distributed_load_client.i: kv_load_client/distributed_load_client.cpp.i
.PHONY : kv_load_client/distributed_load_client.i

# target to preprocess a source file
kv_load_client/distributed_load_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_load_client.dir/build.make CMakeFiles/distributed_load_client.dir/kv_load_client/distributed_load_client.cpp.i
.PHONY : kv_load_client/distributed_load_client.cpp.i

kv_load_client/distributed_load_client.s: kv_load_client/distributed_load_client.cpp.s
.PHONY : kv_load_client/distributed_load_client.s

# target to generate assembly for a file
kv_load_client/distributed_load_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_load_client.dir/build.make CMakeFiles/distributed_load_client.dir/kv_load_client/distributed_load_client.cpp.s
.PHONY : kv_load_client/distributed_load_client.cpp.s

kv_load_client/load_client.o: kv_load_client/load_client.cpp.o
.PHONY : kv_load_client/load_client.o

# target to build an object file
kv_load_client/load_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_client.dir/build.make CMakeFiles/kv_client.dir/kv_load_client/load_client.cpp.o
.PHONY : kv_load_client/load_client.cpp.o

kv_load_client/load_client.i: kv_load_client/load_client.cpp.i
.PHONY : kv_load_client/load_client.i

# target to preprocess a source file
kv_load_client/load_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_client.dir/build.make CMakeFiles/kv_client.dir/kv_load_client/load_client.cpp.i
.PHONY : kv_load_client/load_client.cpp.i

kv_load_client/load_client.s: kv_load_client/load_client.cpp.s
.PHONY : kv_load_client/load_client.s

# target to generate assembly for a file
kv_load_client/load_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_client.dir/build.make CMakeFiles/kv_client.dir/kv_load_client/load_client.cpp.s
.PHONY : kv_load_client/load_client.cpp.s

server/redis_server.o: server/redis_server.cpp.o
.PHONY : server/redis_server.o

# target to build an object file
server/redis_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_server.dir/build.make CMakeFiles/redis_server.dir/server/redis_server.cpp.o
.PHONY : server/redis_server.cpp.o

server/redis_server.i: server/redis_server.cpp.i
.PHONY : server/redis_server.i

# target to preprocess a source file
server/redis_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_server.dir/build.make CMakeFiles/redis_server.dir/server/redis_server.cpp.i
.PHONY : server/redis_server.cpp.i

server/redis_server.s: server/redis_server.cpp.s
.PHONY : server/redis_server.s

# target to generate assembly for a file
server/redis_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_server.dir/build.make CMakeFiles/redis_server.dir/server/redis_server.cpp.s
.PHONY : server/redis_server.cpp.s

server/server.o: server/server.cpp.o
.PHONY : server/server.o

# target to build an object file
server/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_server.dir/build.make CMakeFiles/kv_server.dir/server/server.cpp.o
.PHONY : server/server.cpp.o

server/server.i: server/server.cpp.i
.PHONY : server/server.i

# target to preprocess a source file
server/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_server.dir/build.make CMakeFiles/kv_server.dir/server/server.cpp.i
.PHONY : server/server.cpp.i

server/server.s: server/server.cpp.s
.PHONY : server/server.s

# target to generate assembly for a file
server/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_server.dir/build.make CMakeFiles/kv_server.dir/server/server.cpp.s
.PHONY : server/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... conflict_test"
	@echo "... distributed_load_client"
	@echo "... kv_client"
	@echo "... kv_server"
	@echo "... redis_server"
	@echo "... generated/kv.grpc.pb.o"
	@echo "... generated/kv.grpc.pb.i"
	@echo "... generated/kv.grpc.pb.s"
	@echo "... generated/kv.pb.o"
	@echo "... generated/kv.pb.i"
	@echo "... generated/kv.pb.s"
	@echo "... kv_load_client/conflict_test.o"
	@echo "... kv_load_client/conflict_test.i"
	@echo "... kv_load_client/conflict_test.s"
	@echo "... kv_load_client/distributed_load_client.o"
	@echo "... kv_load_client/distributed_load_client.i"
	@echo "... kv_load_client/distributed_load_client.s"
	@echo "... kv_load_client/load_client.o"
	@echo "... kv_load_client/load_client.i"
	@echo "... kv_load_client/load_client.s"
	@echo "... server/redis_server.o"
	@echo "... server/redis_server.i"
	@echo "... server/redis_server.s"
	@echo "... server/server.o"
	@echo "... server/server.i"
	@echo "... server/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

